name: CI

on: [push]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate build number
        uses: einaregilsson/build-number@v1 
        with:
          token: ${{secrets.github_token}}
      - name: Version notify
        run: |
          curl --header 'Content-Type: application/json' --request POST \
          --data "{\"text\": \"👉🏾 Homepage build *#${BUILD_NUMBER}*: pipeline started.\"}" \
          ${{ DIALOG_WEBHOOK }}
      - name: Update version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          IMAGE_VERSION="$VERSION.$BUILD_NUMBER"
      - name: Upload build number
        uses: actions/upload-artifact@v1
        with:
          name: IMAGE_VERSION
          path: IMAGE_VERSION
      - name: Upload build number
        uses: actions/upload-artifact@v1
        with:
          name: BUILD_NUMBER
          path: BUILD_NUMBER
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      