name: Other CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!develop'

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
      - name: Pipline notify started
        uses: dialogs/dialog-notify-action@master
        with:
          url: ${{ secrets.DIALOG_WEBHOOK }}
          message: '👉🏾 Homepage build: pipeline started. '
      - name: Build
        env:
          EMAIL_USER: ${{secrets.EMAIL_USER}}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          GHOST_ENDPOINT: ${{ secrets.GHOST_ENDPOINT }}
          GHOST_API_KEY: ${{ secrets.GHOST_API_KEY }}
          MAILCHIMP_KEY: ${{ secrets.MAILCHIMP_KEY }}
          MAILCHIMP_LIST_RU: ${{ secrets.MAILCHIMP_LIST_RU }}
          MAILCHIMP_LIST_EN: ${{ secrets.MAILCHIMP_LIST_EN }}
          GATSBY_GRAPHQL_IDE: playground
          DIALOG_WEBHOOK: ${{ secrets.DIALOG_WEBHOOK }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_DSN_PUBLIC: ${{ secrets.SENTRY_DSN_PUBLIC }}
        run: |
          npm ci
          npm run build
      - name: Application notify build
        uses: dialogs/dialog-notify-action@master
        with:
          url: ${{ secrets.DIALOG_WEBHOOK }}
          message: '👉🏾 Homepage build: application build successful.'
